apiVersion: v2
name: servarr
description: One chart to rule all Servarr
type: application
version: 1.6.5
keywords:
  - sonarr
  - servarr
  - radarr
  - overseerr
  - bazarr
  - prowlarr
  - tautulli
  - huntarr
  - cleanuparr
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/Radarr/Radarr
  - https://github.com/sct/overseerr
  - https://github.com/morpheus65535/bazarr
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/tautulli/tautulli
  - https://github.com/plexguide/Huntarr.io
  - https://github.com/Cleanuparr/Cleanuparr
maintainers:
  - name: ntcong
    email: ntcong.it@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
