apiVersion: v2
name: qbittorrent
description: qbittorrent deployment
type: application
version: 1.1.3
keywords:
  - qbittorrent
sources:
  - https://github.com/qbittorrent/qBittorrent
maintainers:
  - name: ntcong
    email: ntcong.it@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
